server:
  port: 8080
spring:
  datasource:
    url: ${DB_URI}/Orders
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URI}
