server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
couchdb:
  username: admin
  password: admin
  database: users
  host: localhost
  port: 5984
