server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Payments
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
