server:
  port: 8082
couchdb:
  username: admin
  password: admin
  database: payments
  host: localhost
  port: 5984

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
