version: "3.7"
services:

  config-service:
    image: wdm/config
    ports:
      - "8888:8888"

  eureka-service:
    image: wdm/config
    ports:
      - "8761:8761"

  orders-service:
    image: wdm/orders
    ports:
      - "8080:8080"

  payments-service:
    image: wdm/payments
    ports:
      - "8081:8081"

  stocks-service:
    image: wdm/stocks
    ports:
      - "8082:8082"

  users-service:
    image: wdm/users
    ports:
      - "8083:8083"
