server:
  port: 8082
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
couchdb:
  username: admin
  password: admin
  database: stock
  host: localhost
  port: 5984
