server:
  port: 8083
spring:
  datasource:
    url: ${DB_URI}/Users
    username: wdm
    password: wdm-2019
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URI}
